server:
  port: 8888
spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2qiaoyu/config-repo
          search-paths: licensingservicem,organizationservice
          username:
          password:
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/